map:
  height: 40
  width: 40
  logic: coverage_ratio # n_rooms/fill_map todo , add t
  layout_count: 10 # number of rooms to add
  coverage_ratio: 0.8 # max is 1 -- the whole room
  timeout: 20
  #amount:
  output_folder: /home/mila/d/daria.yasafova/mini_ada/data/master_maps

layouts:
  directory:
    - directory_1
    - directory_2
    - directory_3
  weight:
    - 1
    - 2
    - 3

# todo later, add a section for training

#layout_connor:
#  - path: path_str
#    value: 0
#  - path: path_str1
#    value: 0


layout_connor:
  - path: /home/mila/d/daria.yasafova/mini_ada/Minigrid/minigrid/templates/
    value: 0.0
  - path: /home/mila/d/daria.yasafova/mini_ada/Minigrid/minigrid/templates/templates_2
    value: 0.0
  - path: /home/mila/d/daria.yasafova/mini_ada/Minigrid/minigrid/templates/layout_3.csv
    value: 0.0
  - path: /home/mila/d/daria.yasafova/mini_ada/Minigrid/minigrid/templates/templates_4
    value: 1
  - path: /home/mila/d/daria.yasafova/mini_ada/Minigrid/minigrid/templates/templates_mazes
    value: 0
  - path: /home/mila/d/daria.yasafova/mini_ada/Minigrid/minigrid/templates/templates_5
    value: 0



    
#layouts: [map_1: {path_1:weight_1}, map_2: {path_2:weight_2},....]

